apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: monitoring
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s

    scrape_configs:
      # Prometheus 자기 자신
      - job_name: "prometheus"
        static_configs:
          - targets: ["localhost:9090"]

      # OTEL Collector scrape
      - job_name: "otel-collector"
        static_configs:
          - targets: ["otel-deployment.monitoring.svc.cluster.local:9464"]
