apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  type: {{ .Values.prometheus.service.type | default "ClusterIP" }}
  selector:
    app: prometheus
  ports:
    - name: http
      port: {{ .Values.prometheus.service.port | default 9090 }}
      targetPort : {{ .Values.prometheus.service.port | default 9090 }}
