prometheus:
  replicaCount: 1
  service:
    type: ClusterIP
    port: 9090
    targetPort: 9090

grafana:
  replicaCount: 1
  service:
    type: NodePort
    port: 3000
    nodePort: 32000

otel-collector:
