apiVersion: v1
kind: Service
metadata:
  name: nginx-lb
  namespace: default
spec:
  type: LoadBalancer
  selector:
    app: nginx-test
  ports:
    - port: 80
      targetPort: 80
  loadBalancerIP: 10.28.100.241   # values.yaml IP 풀 내에서 선택
