grafana:
  replicaCount: 1
  name: grafana
  adminUser: admin
  adminPassword: admin

  service:
    type: ClusterIP
    port: 80
    targetPort: 3000

  persistence:
    enabled: false

  datasources:
    datasources.yaml: |
      apiVersion: 1
      datasources:
        - name: Prometheus
          type: prometheus
          access: proxy
          url: http://prometheus.monitoring.svc.cluster.local
          isDefault: true
