apiVersion: v2
name: ingress-nginx-chart
version: 0.1.0
dependencies:
  - name: ingress-nginx
    version: "4.13.2"
    repository: "https://kubernetes.github.io/ingress-nginx"
  - name: cert-manager
    version: "1.14.0"
    repository: "https://charts.jetstack.io"
