apiVersion: v1
kind: Service
metadata:
  name: ingress-lb
  namespace: network
spec:
  type: LoadBalancer
  selector:
    app: ingress-nginx
  ports:
    - name: http
      port: 80
      targetPort: 80
    - name: https
      port: 443
      targetPort: 443
  loadBalancerIP: 10.28.100.240
