alertmanager:
  enabled: false

pushgateway:
  enabled: false

kubeStateMetrics:
  enabled: false

nodeExporter:
  enabled: false


#server settings
prometheus:
  server:
    image:
      repository: prom/prometheus
      tag: v3.5.0
      pullPolicy: IfNotPresent
    service:
      type: ClusterIP
      port: 80
    replicaCount: 1
    extraScrapeConfigs: |
      - job_name: 'otel-collector'
        static_configs:
          - targets: ['otel-deployment.monitoring.svc.cluster.local:9464']
