alertmanager:
  enabled: false

pushgateway:
  enabled: false

kubeStateMetrics:
  enabled: false

nodeExporter:
  enabled: false


#server settings
prometheus:
  server:
    image:
      repository: prom/prometheus
      tag: v2.48.0
      pullPolicy: IfNotPresent
    service:
      type: ClusterIP
      port: 80
    replicaCount: 1
