{{- range .Values.CertManager.certificates }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .name }}
  namespace: {{ .namespace }}
spec:
  secretName: {{ .secretName }}
  dnsNames: 
{{- range .dnsNames }}
    - "{{ . }}"
{{- end }} 
  issuerRef:
    name: {{ $.Values.CertManager.issuer.name }}
    kind: ClusterIssuer
---
{{- end }}
