{{- if .Values.hubbleIngress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hubble-ui
  namespace: kube-system
spec:
  ingressClassName: nginx
  rules:
    # - host: hubble.retailninsight.com
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.hubbleIngress.serviceName }}
                port:
                  number: {{ .Values.hubbleIngress.servicePort }}
{{- end }}
