kubeProxyReplacement: true 
hubble:
  enabled: true
  ui:
    enabled: true
  relay:
    enabled: true
  metrics:
    enabled: ["dns","drop","tcp","flow","port-distribution","icmp","http"]
hostServices:
  enabled: true
securityContext:
  privileged: true
