apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.grafana.name }}
spec:
  type: {{ .Values.grafana.service.type }}
  ports:
    - port: {{ .Values.grafana.service.port }}
      targetPort: {{ .Values.grafana.service.targetPort }}
  selector:
    app: {{ .Values.grafana.name }}
