apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.otel.deployment.configMap.name }}
data:
  otel-collector-config.yaml: |
    receivers:
      otlp:
        protocols:
          grpc:
          http:

    exporters:
      prometheus:
        endpoint: "0.0.0.0:9464"  # Prometheus scrape용 포트

    service:
      pipelines:
        metrics:
          receivers: [otlp]
          exporters: [prometheus]
